name: Check Skip Commit

on:
  push:
    branches:
      - main

jobs:
  context_log:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined commit messages
        env:
          JOINED_MESSAGES: ${{ join(github.event.commits.*.message) }}
        run: echo "$JOINED_MESSAGES"
      - name: contains skip?
        env:
          SKIP: ${{ contains(join(github.event.commits.*.message), '#skip' ) }}
        run: echo "SKIP $SKIP"